services:
  api:
      container_name: "oneCloud-api"
      image: "oneCloud-api"
      environment:
        DATABASE_HOST: localhsot
        DATABASE_NAME: postgres
        DATABASE_USER: oneCloud-api
        DATABASE_PASSWORD: 123
        DATABASE_PORT: 5432
      build:
        context: ../
        dockerfile: Dockerfile
      entrypoint: ["npm", "run", "start:prod"]
      ports:
        - 3000:3000
      volumes:
        - ./app:/usr/src/app
        - /usr/src/app/node_modules
  mysql:
    image: postgres:latest
    container_name: oneCloud-api
    restart: always
    ports:
    - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: oneCloud-api
    volumes:
       - ./data/db:/var/lib/postgresql
volumes:
  db:
    driver: local